compressionLevel: mixed

enableGlobalCache: false

# Do not send stuff to Meta
enableTelemetry: false

# Disable all postinstall scripts
enableScripts: false

# Use classical node-modules
nodeLinker: node-modules

# Require at least 7 days old packages
npmMinimalAgeGate: "7d"
