/* eslint-disable @typescript-eslint/no-unused-vars */

/**
 * A parsed path object generated by path.parse() or consumed by path.format().
 */
interface ParsedPath {
  /**
   * The root of the path such as '/' or 'c:\'
   */
  root: string
  /**
   * The full directory path such as '/home/user/dir' or 'c:\path\dir'
   */
  dir: string
  /**
   * The file name including extension (if any) such as 'index.html'
   */
  base: string
  /**
   * The file extension (if any) such as '.html'
   */
  ext: string
  /**
   * The file name without extension (if any) such as 'index'
   */
  name: string
}

interface FormatInputPathObject {
  /**
   * The root of the path such as '/' or 'c:\'
   */
  root?: string | undefined
  /**
   * The full directory path such as '/home/user/dir' or 'c:\path\dir'
   */
  dir?: string | undefined
  /**
   * The file name including extension (if any) such as 'index.html'
   */
  base?: string | undefined
  /**
   * The file extension (if any) such as '.html'
   */
  ext?: string | undefined
  /**
   * The file name without extension (if any) such as 'index'
   */
  name?: string | undefined
}
