name: Lint PO-Files

# On every push to the lang folder, and whenever another workflow calls this one
on:
  workflow_call: {}
  push:
    paths:
      - static/lang/**
  pull_request:
    paths:
      - static/lang/**

permissions:
  contents: read

# Ensure only a single linter workflow runs at any one time for any event and
# ref. This allows multiple linters to run, but at most one per ref.
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  po_lint:
    name: Lint PO-Files
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      with:
        # Always fetch the branch that triggered the event (develop or master)
        ref: ${{ github.ref }}
    - name: Setup Node and Yarn
      uses: ./.github/actions/setup-yarn
    - name: Run lint:po
      run: yarn lint:po
