name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        # Always fetch the branch that triggered the event (develop or master)
        ref: ${{ github.ref }}
    - name: Setup NodeJS 16
      uses: actions/setup-node@v1
      with:
        node-version: '16'
    - name: Install packages
      run: yarn install --frozen-lockfile
    - name: Run the unit tests
      run: yarn test
    - name: Test reveal.JS template pre-building
      run: yarn reveal:build
    - name: Test CSL refreshing
      run: yarn csl:refresh
